import { GFXDevice } from './device';
import { GFXBuffer } from './buffer';
import { GFXTexture } from './texture';
import { GFXTextureView } from './texture-view';
import { GFXSampler } from './sampler';
import { GFXShader } from './shader';
import { GFXInputAssembler } from './input-assembler';
import { GFXRenderPass } from './render-pass';
import { GFXFramebuffer } from './framebuffer';
import { GFXPipelineLayout } from './pipeline-layout';
import { GFXPipelineState } from './pipeline-state';
import { GFXCommandBuffer } from './command-buffer';
import { GFXQueue } from './queue';
import { WebGLGFXDevice } from './webgl/webgl-device';

cc.GFXDevice = GFXDevice;
cc.GFXBuffer = GFXBuffer;
cc.GFXTexture = GFXTexture;
cc.GFXTextureView = GFXTextureView;
cc.GFXSampler = GFXSampler;
cc.GFXShader = GFXShader;
cc.GFXInputAssembler = GFXInputAssembler;
cc.GFXRenderPass = GFXRenderPass;
cc.GFXFramebuffer = GFXFramebuffer;
cc.GFXPipelineLayout = GFXPipelineLayout;
cc.GFXPipelineState = GFXPipelineState;
cc.GFXCommandBuffer = GFXCommandBuffer;
cc.GFXQueue = GFXQueue;
cc.WebGLGFXDevice = WebGLGFXDevice;
