// app.js
App({
  GameGlobal: {
    screencanvas: undefined,
    canvas: undefined,
    System: undefined,
    Image: undefined,
    cc: undefined,
    CocosEngine: undefined,
    ccwindow: undefined,
    fsUtils: undefined,
    document: undefined,
    requestAnimationFrame: undefined,
    cancelAnimationFrame: undefined,
    Image: undefined,
    ImageBitmap: undefined,
    XMLHttpRequest: undefined,
    WebSocket: undefined,
    DOMParser: undefined,
    WebAssembly: undefined,
    WXWebAssembly: undefined,
    CCWebAssembly: undefined,
    _touchStart: undefined,
    _touchMove: undefined,
    _touchEnd: undefined,
    _touchCancel: undefined,
    showInput: false,
    indexThis: undefined,
    _onKeyboardInput: undefined,
    _onKeyboardConfirm: undefined,
    _onKeyboardComplete: undefined,
  },
  onLaunch() {
  },
})
