#ifndef __JS_TEMPLATE_RUNTIME_FRAMEWORKS_RUNTIME_SRC_CLASSES_JS_MODULE_REGISTER_H__
#define __JS_TEMPLATE_RUNTIME_FRAMEWORKS_RUNTIME_SRC_CLASSES_JS_MODULE_REGISTER_H__

#include "scripting/js-bindings/manual/ScriptingCore.h"

int js_module_register();

extern JSObject *jsb_cocos2d_FileUtils_prototype;
JSObject* get_jsb_cocos2d_FileUtils_prototype();

#endif  // __JS_TEMPLATE_RUNTIME_FRAMEWORKS_RUNTIME_SRC_CLASSES_JS_MODULE_REGISTER_H__

