// clang-format off

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/****************************************************************************
 Copyright (c) 2022 Xiamen Yaji Software Co., Ltd.

 http://www.cocos.com

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated engine source code (the "Software"), a limited,
 worldwide, royalty-free, non-assignable, revocable and non-exclusive license
 to use Cocos Creator solely to develop games on your target platforms. You shall
 not use Cocos Creator software for developing other software or tools that's
 used for developing games. You are not granted to publish, distribute,
 sublicense, and/or sell copies of Cocos Creator.

 The software or tools in this License Agreement are licensed, not sold.
 Xiamen Yaji Software Co., Ltd. reserves all rights not expressly granted to you.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
****************************************************************************/

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static 
#endif



#include <stdio.h>


#include "bindings/jswrapper/SeApi.h"
#include "bindings/manual/jsb_conversions.h"
#include "bindings/manual/jsb_global.h"


#include "bindings/auto/jsb_video_auto.h"



se::Class* __jsb_cc_VideoPlayer_class = nullptr;
se::Object* __jsb_cc_VideoPlayer_proto = nullptr;
SE_DECLARE_FINALIZE_FUNC(js_delete_cc_VideoPlayer) 

// js_ctor
static bool js_new_cc_VideoPlayer(se::State& s) // NOLINT(readability-identifier-naming)
{
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    
    cc::VideoPlayer *result;
    result = (cc::VideoPlayer *)new cc::VideoPlayer();
    
    
    auto *ptr = JSB_MAKE_PRIVATE_OBJECT_WITH_INSTANCE(result);
    s.thisObject()->setPrivateObject(ptr);
    return true;
}
SE_BIND_CTOR(js_new_cc_VideoPlayer, __jsb_cc_VideoPlayer_class, js_delete_cc_VideoPlayer)

static bool js_delete_cc_VideoPlayer(se::State& s)
{
    // js_dtoroverride
    return true;
}
SE_BIND_FINALIZE_FUNC(js_delete_cc_VideoPlayer) 

static bool js_cc_VideoPlayer_destroy(se::State& s)
{
    // js_function
    
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    cc::VideoPlayer *arg1 = (cc::VideoPlayer *) NULL ;
    
    if(argc != 0) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 0);
        return false;
    }
    arg1 = SE_THIS_OBJECT<cc::VideoPlayer>(s);
    SE_PRECONDITION2(arg1, false, "%s: Invalid Native Object", __FUNCTION__); 
    (arg1)->destroy();
    
    
    return true;
}
SE_BIND_FUNC(js_cc_VideoPlayer_destroy) 

static bool js_cc_VideoPlayer_setURL(se::State& s)
{
    // js_function
    
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    cc::VideoPlayer *arg1 = (cc::VideoPlayer *) NULL ;
    ccstd::string *arg2 = 0 ;
    ccstd::string temp2 ;
    
    if(argc != 1) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 1);
        return false;
    }
    arg1 = SE_THIS_OBJECT<cc::VideoPlayer>(s);
    SE_PRECONDITION2(arg1, false, "%s: Invalid Native Object", __FUNCTION__); 
    // %typemap(in) SWIGTYPE&
    ok &= sevalue_to_native(args[0], &temp2, s.thisObject());
    SE_PRECONDITION2(ok, false, "VideoPlayer_setURL,2,SWIGTYPE_p_ccstd__string");
    arg2 = &temp2;
    
    (arg1)->setURL((ccstd::string const &)*arg2);
    
    
    return true;
}
SE_BIND_FUNC(js_cc_VideoPlayer_setURL) 

static bool js_cc_VideoPlayer_play(se::State& s)
{
    // js_function
    
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    cc::VideoPlayer *arg1 = (cc::VideoPlayer *) NULL ;
    
    if(argc != 0) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 0);
        return false;
    }
    arg1 = SE_THIS_OBJECT<cc::VideoPlayer>(s);
    SE_PRECONDITION2(arg1, false, "%s: Invalid Native Object", __FUNCTION__); 
    (arg1)->play();
    
    
    return true;
}
SE_BIND_FUNC(js_cc_VideoPlayer_play) 

static bool js_cc_VideoPlayer_pause(se::State& s)
{
    // js_function
    
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    cc::VideoPlayer *arg1 = (cc::VideoPlayer *) NULL ;
    
    if(argc != 0) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 0);
        return false;
    }
    arg1 = SE_THIS_OBJECT<cc::VideoPlayer>(s);
    SE_PRECONDITION2(arg1, false, "%s: Invalid Native Object", __FUNCTION__); 
    (arg1)->pause();
    
    
    return true;
}
SE_BIND_FUNC(js_cc_VideoPlayer_pause) 

static bool js_cc_VideoPlayer_stop(se::State& s)
{
    // js_function
    
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    cc::VideoPlayer *arg1 = (cc::VideoPlayer *) NULL ;
    
    if(argc != 0) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 0);
        return false;
    }
    arg1 = SE_THIS_OBJECT<cc::VideoPlayer>(s);
    SE_PRECONDITION2(arg1, false, "%s: Invalid Native Object", __FUNCTION__); 
    (arg1)->stop();
    
    
    return true;
}
SE_BIND_FUNC(js_cc_VideoPlayer_stop) 

static bool js_cc_VideoPlayer_seekTo(se::State& s)
{
    // js_function
    
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    cc::VideoPlayer *arg1 = (cc::VideoPlayer *) NULL ;
    float arg2 ;
    
    if(argc != 1) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 1);
        return false;
    }
    arg1 = SE_THIS_OBJECT<cc::VideoPlayer>(s);
    SE_PRECONDITION2(arg1, false, "%s: Invalid Native Object", __FUNCTION__); 
    // %typemap(in) int, short, long, signed char, float, double
    ok &= sevalue_to_native(args[0], &arg2, nullptr);
    SE_PRECONDITION2(ok, false, "VideoPlayer_seekTo,2,SWIGTYPE_float"); 
    (arg1)->seekTo(arg2);
    
    
    return true;
}
SE_BIND_FUNC(js_cc_VideoPlayer_seekTo) 

static bool js_cc_VideoPlayer_currentTime(se::State& s)
{
    // js_function
    
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    cc::VideoPlayer *arg1 = (cc::VideoPlayer *) NULL ;
    float result;
    
    if(argc != 0) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 0);
        return false;
    }
    arg1 = SE_THIS_OBJECT<cc::VideoPlayer>(s);
    SE_PRECONDITION2(arg1, false, "%s: Invalid Native Object", __FUNCTION__); 
    result = (float)((cc::VideoPlayer const *)arg1)->currentTime();
    
    // out 1
    ok &= nativevalue_to_se(result, s.rval(), s.thisObject() /*ctx*/); 
    
    
    return true;
}
SE_BIND_FUNC(js_cc_VideoPlayer_currentTime) 

static bool js_cc_VideoPlayer_duration(se::State& s)
{
    // js_function
    
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    cc::VideoPlayer *arg1 = (cc::VideoPlayer *) NULL ;
    float result;
    
    if(argc != 0) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 0);
        return false;
    }
    arg1 = SE_THIS_OBJECT<cc::VideoPlayer>(s);
    SE_PRECONDITION2(arg1, false, "%s: Invalid Native Object", __FUNCTION__); 
    result = (float)((cc::VideoPlayer const *)arg1)->duration();
    
    // out 1
    ok &= nativevalue_to_se(result, s.rval(), s.thisObject() /*ctx*/); 
    
    
    return true;
}
SE_BIND_FUNC(js_cc_VideoPlayer_duration) 

static bool js_cc_VideoPlayer_setKeepAspectRatioEnabled(se::State& s)
{
    // js_function
    
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    cc::VideoPlayer *arg1 = (cc::VideoPlayer *) NULL ;
    bool arg2 ;
    
    if(argc != 1) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 1);
        return false;
    }
    arg1 = SE_THIS_OBJECT<cc::VideoPlayer>(s);
    SE_PRECONDITION2(arg1, false, "%s: Invalid Native Object", __FUNCTION__); 
    // %typemap(in) bool
    ok &= sevalue_to_native(args[0], &arg2);
    SE_PRECONDITION2(ok, false, "VideoPlayer_setKeepAspectRatioEnabled,2,SWIGTYPE_bool"); 
    (arg1)->setKeepAspectRatioEnabled(arg2);
    
    
    return true;
}
SE_BIND_FUNC(js_cc_VideoPlayer_setKeepAspectRatioEnabled) 

static bool js_cc_VideoPlayer_isKeepAspectRatioEnabled(se::State& s)
{
    // js_function
    
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    cc::VideoPlayer *arg1 = (cc::VideoPlayer *) NULL ;
    bool result;
    
    if(argc != 0) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 0);
        return false;
    }
    arg1 = SE_THIS_OBJECT<cc::VideoPlayer>(s);
    SE_PRECONDITION2(arg1, false, "%s: Invalid Native Object", __FUNCTION__); 
    result = (bool)((cc::VideoPlayer const *)arg1)->isKeepAspectRatioEnabled();
    // out 5
    ok &= nativevalue_to_se(result, s.rval(), s.thisObject() /*ctx*/);
    
    
    return true;
}
SE_BIND_FUNC(js_cc_VideoPlayer_isKeepAspectRatioEnabled) 

static bool js_cc_VideoPlayer_setFullScreenEnabled(se::State& s)
{
    // js_function
    
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    cc::VideoPlayer *arg1 = (cc::VideoPlayer *) NULL ;
    bool arg2 ;
    
    if(argc != 1) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 1);
        return false;
    }
    arg1 = SE_THIS_OBJECT<cc::VideoPlayer>(s);
    SE_PRECONDITION2(arg1, false, "%s: Invalid Native Object", __FUNCTION__); 
    // %typemap(in) bool
    ok &= sevalue_to_native(args[0], &arg2);
    SE_PRECONDITION2(ok, false, "VideoPlayer_setFullScreenEnabled,2,SWIGTYPE_bool"); 
    (arg1)->setFullScreenEnabled(arg2);
    
    
    return true;
}
SE_BIND_FUNC(js_cc_VideoPlayer_setFullScreenEnabled) 

static bool js_cc_VideoPlayer_addEventListener(se::State& s)
{
    // js_function
    
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    cc::VideoPlayer *arg1 = (cc::VideoPlayer *) NULL ;
    ccstd::string *arg2 = 0 ;
    cc::VideoPlayer::ccVideoPlayerCallback *arg3 = 0 ;
    ccstd::string temp2 ;
    cc::VideoPlayer::ccVideoPlayerCallback temp3 ;
    
    if(argc != 2) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 2);
        return false;
    }
    arg1 = SE_THIS_OBJECT<cc::VideoPlayer>(s);
    SE_PRECONDITION2(arg1, false, "%s: Invalid Native Object", __FUNCTION__); 
    // %typemap(in) SWIGTYPE&
    ok &= sevalue_to_native(args[0], &temp2, s.thisObject());
    SE_PRECONDITION2(ok, false, "VideoPlayer_addEventListener,2,SWIGTYPE_p_ccstd__string");
    arg2 = &temp2;
    
    // %typemap(in) SWIGTYPE&
    ok &= sevalue_to_native(args[1], &temp3, s.thisObject());
    SE_PRECONDITION2(ok, false, "VideoPlayer_addEventListener,3,SWIGTYPE_p_std__functionT_void_fF_t");
    arg3 = &temp3;
    
    (arg1)->addEventListener((ccstd::string const &)*arg2,(cc::VideoPlayer::ccVideoPlayerCallback const &)*arg3);
    
    
    return true;
}
SE_BIND_FUNC(js_cc_VideoPlayer_addEventListener) 

static bool js_cc_VideoPlayer_onPlayEvent(se::State& s)
{
    // js_function
    
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    cc::VideoPlayer *arg1 = (cc::VideoPlayer *) NULL ;
    int arg2 ;
    
    if(argc != 1) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 1);
        return false;
    }
    arg1 = SE_THIS_OBJECT<cc::VideoPlayer>(s);
    SE_PRECONDITION2(arg1, false, "%s: Invalid Native Object", __FUNCTION__); 
    // %typemap(in) int, short, long, signed char, float, double
    ok &= sevalue_to_native(args[0], &arg2, nullptr);
    SE_PRECONDITION2(ok, false, "VideoPlayer_onPlayEvent,2,SWIGTYPE_int"); 
    (arg1)->onPlayEvent(arg2);
    
    
    return true;
}
SE_BIND_FUNC(js_cc_VideoPlayer_onPlayEvent) 

static bool js_cc_VideoPlayer_setVisible(se::State& s)
{
    // js_function
    
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    cc::VideoPlayer *arg1 = (cc::VideoPlayer *) NULL ;
    bool arg2 ;
    
    if(argc != 1) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 1);
        return false;
    }
    arg1 = SE_THIS_OBJECT<cc::VideoPlayer>(s);
    SE_PRECONDITION2(arg1, false, "%s: Invalid Native Object", __FUNCTION__); 
    // %typemap(in) bool
    ok &= sevalue_to_native(args[0], &arg2);
    SE_PRECONDITION2(ok, false, "VideoPlayer_setVisible,2,SWIGTYPE_bool"); 
    (arg1)->setVisible(arg2);
    
    
    return true;
}
SE_BIND_FUNC(js_cc_VideoPlayer_setVisible) 

static bool js_cc_VideoPlayer_setFrame(se::State& s)
{
    // js_function
    
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    cc::VideoPlayer *arg1 = (cc::VideoPlayer *) NULL ;
    float arg2 ;
    float arg3 ;
    float arg4 ;
    float arg5 ;
    
    if(argc != 4) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 4);
        return false;
    }
    arg1 = SE_THIS_OBJECT<cc::VideoPlayer>(s);
    SE_PRECONDITION2(arg1, false, "%s: Invalid Native Object", __FUNCTION__); 
    // %typemap(in) int, short, long, signed char, float, double
    ok &= sevalue_to_native(args[0], &arg2, nullptr);
    SE_PRECONDITION2(ok, false, "VideoPlayer_setFrame,2,SWIGTYPE_float"); 
    // %typemap(in) int, short, long, signed char, float, double
    ok &= sevalue_to_native(args[1], &arg3, nullptr);
    SE_PRECONDITION2(ok, false, "VideoPlayer_setFrame,3,SWIGTYPE_float"); 
    // %typemap(in) int, short, long, signed char, float, double
    ok &= sevalue_to_native(args[2], &arg4, nullptr);
    SE_PRECONDITION2(ok, false, "VideoPlayer_setFrame,4,SWIGTYPE_float"); 
    // %typemap(in) int, short, long, signed char, float, double
    ok &= sevalue_to_native(args[3], &arg5, nullptr);
    SE_PRECONDITION2(ok, false, "VideoPlayer_setFrame,5,SWIGTYPE_float"); 
    (arg1)->setFrame(arg2,arg3,arg4,arg5);
    
    
    return true;
}
SE_BIND_FUNC(js_cc_VideoPlayer_setFrame) 

bool js_register_cc_VideoPlayer(se::Object* obj) {
    auto* cls = se::Class::create("VideoPlayer", obj, nullptr, _SE(js_new_cc_VideoPlayer)); 
    
    
    cls->defineFunction("destroy", _SE(js_cc_VideoPlayer_destroy)); 
    cls->defineFunction("setURL", _SE(js_cc_VideoPlayer_setURL)); 
    cls->defineFunction("play", _SE(js_cc_VideoPlayer_play)); 
    cls->defineFunction("pause", _SE(js_cc_VideoPlayer_pause)); 
    cls->defineFunction("stop", _SE(js_cc_VideoPlayer_stop)); 
    cls->defineFunction("seekTo", _SE(js_cc_VideoPlayer_seekTo)); 
    cls->defineFunction("currentTime", _SE(js_cc_VideoPlayer_currentTime)); 
    cls->defineFunction("duration", _SE(js_cc_VideoPlayer_duration)); 
    cls->defineFunction("setKeepAspectRatioEnabled", _SE(js_cc_VideoPlayer_setKeepAspectRatioEnabled)); 
    cls->defineFunction("isKeepAspectRatioEnabled", _SE(js_cc_VideoPlayer_isKeepAspectRatioEnabled)); 
    cls->defineFunction("setFullScreenEnabled", _SE(js_cc_VideoPlayer_setFullScreenEnabled)); 
    cls->defineFunction("addEventListener", _SE(js_cc_VideoPlayer_addEventListener)); 
    cls->defineFunction("onPlayEvent", _SE(js_cc_VideoPlayer_onPlayEvent)); 
    cls->defineFunction("setVisible", _SE(js_cc_VideoPlayer_setVisible)); 
    cls->defineFunction("setFrame", _SE(js_cc_VideoPlayer_setFrame)); 
    
    
    
    
    cls->defineFinalizeFunction(_SE(js_delete_cc_VideoPlayer));
    
    
    cls->install();
    JSBClassType::registerClass<cc::VideoPlayer>(cls);
    
    __jsb_cc_VideoPlayer_proto = cls->getProto();
    __jsb_cc_VideoPlayer_class = cls;
    se::ScriptEngine::getInstance()->clearException();
    return true;
}




bool register_all_video(se::Object* obj) {
    // Get the ns
    se::Value nsVal;
    if (!obj->getProperty("jsb", &nsVal, true))
    {
        se::HandleObject jsobj(se::Object::createPlainObject());
        nsVal.setObject(jsobj);
        obj->setProperty("jsb", nsVal);
    }
    se::Object* ns = nsVal.toObject();
    /* Register classes */
    js_register_cc_VideoPlayer(ns); 
    
    /* Register global variables & global functions */
    
    
    
    return true;
}

// clang-format on
