// clang-format off

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.1.0
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/****************************************************************************
 Copyright (c) 2022 Xiamen Yaji Software Co., Ltd.

 http://www.cocos.com

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated engine source code (the "Software"), a limited,
 worldwide, royalty-free, non-assignable, revocable and non-exclusive license
 to use Cocos Creator solely to develop games on your target platforms. You shall
 not use Cocos Creator software for developing other software or tools that's
 used for developing games. You are not granted to publish, distribute,
 sublicense, and/or sell copies of Cocos Creator.

 The software or tools in this License Agreement are licensed, not sold.
 Xiamen Yaji Software Co., Ltd. reserves all rights not expressly granted to you.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
****************************************************************************/

#pragma once
#include "bindings/jswrapper/SeApi.h"
#include "bindings/manual/jsb_conversions.h"
#include "editor-support/dragonbones-creator-support/CCDragonBonesHeaders.h"



bool register_all_dragonbones(se::Object* obj);


JSB_REGISTER_OBJECT_TYPE(dragonBones::Rectangle);
extern se::Object *__jsb_dragonBones_Rectangle_proto; // NOLINT
extern se::Class * __jsb_dragonBones_Rectangle_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::Transform);
extern se::Object *__jsb_dragonBones_Transform_proto; // NOLINT
extern se::Class * __jsb_dragonBones_Transform_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::Matrix);
extern se::Object *__jsb_dragonBones_Matrix_proto; // NOLINT
extern se::Class * __jsb_dragonBones_Matrix_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::BaseObject);
extern se::Object *__jsb_dragonBones_BaseObject_proto; // NOLINT
extern se::Class * __jsb_dragonBones_BaseObject_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::EventObject);
extern se::Object *__jsb_dragonBones_EventObject_proto; // NOLINT
extern se::Class * __jsb_dragonBones_EventObject_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::BaseFactory);
extern se::Object *__jsb_dragonBones_BaseFactory_proto; // NOLINT
extern se::Class * __jsb_dragonBones_BaseFactory_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::BuildArmaturePackage);
extern se::Object *__jsb_dragonBones_BuildArmaturePackage_proto; // NOLINT
extern se::Class * __jsb_dragonBones_BuildArmaturePackage_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::DragonBonesData);
extern se::Object *__jsb_dragonBones_DragonBonesData_proto; // NOLINT
extern se::Class * __jsb_dragonBones_DragonBonesData_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::TextureAtlasData);
extern se::Object *__jsb_dragonBones_TextureAtlasData_proto; // NOLINT
extern se::Class * __jsb_dragonBones_TextureAtlasData_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::TextureData);
extern se::Object *__jsb_dragonBones_TextureData_proto; // NOLINT
extern se::Class * __jsb_dragonBones_TextureData_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::ArmatureData);
extern se::Object *__jsb_dragonBones_ArmatureData_proto; // NOLINT
extern se::Class * __jsb_dragonBones_ArmatureData_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::BoneData);
extern se::Object *__jsb_dragonBones_BoneData_proto; // NOLINT
extern se::Class * __jsb_dragonBones_BoneData_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::SlotData);
extern se::Object *__jsb_dragonBones_SlotData_proto; // NOLINT
extern se::Class * __jsb_dragonBones_SlotData_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::SkinData);
extern se::Object *__jsb_dragonBones_SkinData_proto; // NOLINT
extern se::Class * __jsb_dragonBones_SkinData_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::AnimationData);
extern se::Object *__jsb_dragonBones_AnimationData_proto; // NOLINT
extern se::Class * __jsb_dragonBones_AnimationData_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::TimelineData);
extern se::Object *__jsb_dragonBones_TimelineData_proto; // NOLINT
extern se::Class * __jsb_dragonBones_TimelineData_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::WorldClock);
extern se::Object *__jsb_dragonBones_WorldClock_proto; // NOLINT
extern se::Class * __jsb_dragonBones_WorldClock_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::Animation);
extern se::Object *__jsb_dragonBones_Animation_proto; // NOLINT
extern se::Class * __jsb_dragonBones_Animation_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::AnimationState);
extern se::Object *__jsb_dragonBones_AnimationState_proto; // NOLINT
extern se::Class * __jsb_dragonBones_AnimationState_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::BonePose);
extern se::Object *__jsb_dragonBones_BonePose_proto; // NOLINT
extern se::Class * __jsb_dragonBones_BonePose_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::BlendState);
extern se::Object *__jsb_dragonBones_BlendState_proto; // NOLINT
extern se::Class * __jsb_dragonBones_BlendState_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::TransformObject);
extern se::Object *__jsb_dragonBones_TransformObject_proto; // NOLINT
extern se::Class * __jsb_dragonBones_TransformObject_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::Slot);
extern se::Object *__jsb_dragonBones_Slot_proto; // NOLINT
extern se::Class * __jsb_dragonBones_Slot_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::Bone);
extern se::Object *__jsb_dragonBones_Bone_proto; // NOLINT
extern se::Class * __jsb_dragonBones_Bone_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::Armature);
extern se::Object *__jsb_dragonBones_Armature_proto; // NOLINT
extern se::Class * __jsb_dragonBones_Armature_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::CCArmatureDisplay);
extern se::Object *__jsb_dragonBones_CCArmatureDisplay_proto; // NOLINT
extern se::Class * __jsb_dragonBones_CCArmatureDisplay_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::CCFactory);
extern se::Object *__jsb_dragonBones_CCFactory_proto; // NOLINT
extern se::Class * __jsb_dragonBones_CCFactory_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::CCSlot);
extern se::Object *__jsb_dragonBones_CCSlot_proto; // NOLINT
extern se::Class * __jsb_dragonBones_CCSlot_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::CCArmatureCacheDisplay);
extern se::Object *__jsb_dragonBones_CCArmatureCacheDisplay_proto; // NOLINT
extern se::Class * __jsb_dragonBones_CCArmatureCacheDisplay_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::ArmatureCache);
extern se::Object *__jsb_dragonBones_ArmatureCache_proto; // NOLINT
extern se::Class * __jsb_dragonBones_ArmatureCache_class; // NOLINT


JSB_REGISTER_OBJECT_TYPE(dragonBones::ArmatureCacheMgr);
extern se::Object *__jsb_dragonBones_ArmatureCacheMgr_proto; // NOLINT
extern se::Class * __jsb_dragonBones_ArmatureCacheMgr_class; // NOLINT

// clang-format on
