module.exports = [
    [cc,   'Node',           require('./node'),            'Node'],
    [cc,   'SpriteBatchNode',require('./sprite-batch-node'), 'SpriteBatchNode'],
    [cc,   'LabelBMFont',    require('./bitmap-font'),     'LabelBMFont'],
    [cc,   'LabelTTF',       require('./label-ttf'),       'LabelTTF'],
    [cc,   'ParticleSystem', require('./particle'),        'ParticleSystem'],
    [cc,   'ProgressTimer',  require('./progress-timer'),  'ProgressTimer'],
    [cc,   'TMXTiledMap',    require('./tiled-map')],
    [cc,   'Layer',          require('./layer'),           'Layer'],
    [cc,   'LayerColor',     require('./layer-color'),     'LayerColor'],
    [cc,   'DrawNode',       require('./draw-node'),       'DrawNode'],
    [cc,   'EditBox',        require('./edit-box'),        'EditBox'],

    [ccui, 'Button',         require('./ui/button'),       'UI/Button'],
    [ccui, 'ImageView',      require('./ui/scale9-sprite'),'UI/Scale9Sprite'],
    [ccui, 'CheckBox',       require('./ui/check-box'),    'UI/CheckBox'],
    [ccui, 'LoadingBar',     require('./ui/loading-bar'),  'UI/LoadingBar'],
    [ccui, 'Slider',         require('./ui/slider'),       'UI/Slider'],
    [ccui, 'ScrollView',     require('./ui/scroll-view'),  'UI/ScrollView'],
    [ccui, 'ListView',       require('./ui/list-view'),    'UI/ListView'],
    [ccui, 'PageView',       require('./ui/page-view'),    'UI/PageView'],
    [ccui, 'Layout',         require('./ui/layout'),       'UI/Layout'],
    [ccui, 'Text',           require('./ui/text'),         'UI/Text'],
    [ccui, 'TextField',      require('./ui/text-field'),   'UI/TextField'],
    [ccui, 'TextAtlas',      require('./ui/text-atlas'),   'UI/TextAtlas'],
    [ccui, 'TextBMFont',     require('./ui/text-bitmap-font'), 'UI/TextBMFont'],
];
