#pragma once

#include <cstdint>

namespace cc {
namespace ohos {
enum {
    ABILITY_CMD_INPUT_CHANGED,
    ABILITY_CMD_INIT_WINDOW,
    ABILITY_CMD_TERM_WINDOW,
    ABILITY_CMD_WINDOW_RESIZED,
    ABILITY_CMD_WINDOW_REDRAW_NEEDED,
    ABILITY_CMD_CONTENT_RECT_CHANGED,
    ABILITY_CMD_GAINED_FOCUS,
    ABILITY_CMD_LOST_FOCUS,
    ABILITY_CMD_CONFIG_CHANGED,
    ABILITY_CMD_LOW_MEMORY,
    ABILITY_CMD_START,
    ABILITY_CMD_RESUME,
    ABILITY_CMD_SAVE_STATE,
    ABILITY_CMD_PAUSE,
    ABILITY_CMD_STOP,
    ABILITY_CMD_DESTROY,
};
} // namespace ohos
} // namespace cc