export const fieldDecorators = [
    "property",
    // serializable
    "serializable",
    "formerlySerializedAs",
    "editorOnly",
    "uniquelyReferenced",
    // editor
    "type",
    "override",
    "executeInEditMode",
    "menu",
    "playOnFocus",
    "inspector",
    "icon",
    "help",
    "editable",
    "visible",
    "readOnly",
    "displayName",
    "tooltip",
    "group",
    "range",
    "rangeMin",
    "rangeMax",
    "rangeStep",
    "slide",
    "displayOrder",
    "unit",
    "radian",
    "multiline",
    "disallowAnimation",
    // component
    "requireComponent",
    "executionOrder",
    "disallowMultiple",
    "allowReplicated",
    // ccclass
    "ccclass",
];

export const editorDecorators = [
    "executeInEditMode",
    "menu",
    "playOnFocus",
    "inspector",
    "icon",
    "help",
    "editable",
    "visible",
    "readOnly",
    "displayName",
    "tooltip",
    "group",
    "range",
    "rangeMin",
    "rangeMax",
    "rangeStep",
    "slide",
    "displayOrder",
    "unit",
    "radian",
    "multiline",
    "disallowAnimation",
];


