set(GFX_GLES_NEW_FILES
        cocos/renderer/gfx-gles-new/GLESBuffer.cpp
        cocos/renderer/gfx-gles-new/GLESBuffer.h
        cocos/renderer/gfx-gles-new/GLESTexture.h
        cocos/renderer/gfx-gles-new/GLESTexture.cpp
        cocos/renderer/gfx-gles-new/GLESDevice.h
        cocos/renderer/gfx-gles-new/GLESInputAssembler.cpp
        cocos/renderer/gfx-gles-new/GLESInputAssembler.h
        cocos/renderer/gfx-gles-new/GLESDevice.cpp
        cocos/renderer/gfx-gles-new/GLESQueue.h
        cocos/renderer/gfx-gles-new/GLESQueue.cpp
        cocos/renderer/gfx-gles-new/GLESSwapchain.cpp
        cocos/renderer/gfx-gles-new/GLESSwapchain.h
        cocos/renderer/gfx-gles-new/GLESConversion.cpp
        cocos/renderer/gfx-gles-new/GLESConversion.h
        cocos/renderer/gfx-gles-new/GLESFramebuffer.cpp
        cocos/renderer/gfx-gles-new/GLESFramebuffer.h
        cocos/renderer/gfx-gles-new/GLESRenderPass.cpp
        cocos/renderer/gfx-gles-new/GLESRenderPass.h
        cocos/renderer/gfx-gles-new/GLESDescriptorSet.cpp
        cocos/renderer/gfx-gles-new/GLESDescriptorSet.h
        cocos/renderer/gfx-gles-new/GLESDescriptorSetLayout.cpp
        cocos/renderer/gfx-gles-new/GLESDescriptorSetLayout.h
        cocos/renderer/gfx-gles-new/GLESPipelineLayout.cpp
        cocos/renderer/gfx-gles-new/GLESPipelineLayout.h
        cocos/renderer/gfx-gles-new/GLESSampler.cpp
        cocos/renderer/gfx-gles-new/GLESSampler.h
        cocos/renderer/gfx-gles-new/GLESShader.cpp
        cocos/renderer/gfx-gles-new/GLESShader.h
        cocos/renderer/gfx-gles-new/GLESPipelineState.cpp
        cocos/renderer/gfx-gles-new/GLESPipelineState.h
        cocos/renderer/gfx-gles-new/GLESCommandBuffer.cpp
        cocos/renderer/gfx-gles-new/GLESCommandBuffer.h
        cocos/renderer/gfx-gles-new/GLESCommandStorage.cpp
        cocos/renderer/gfx-gles-new/GLESCommandStorage.h
        cocos/renderer/gfx-gles-new/GLESCommands.cpp
        cocos/renderer/gfx-gles-new/GLESCommands.h
        cocos/renderer/gfx-gles-new/egl/Context.h
        cocos/renderer/gfx-gles-new/egl/Context.cpp
        cocos/renderer/gfx-gles-new/egl/Wrapper.h
        cocos/renderer/gfx-gles-new/egl/Wrapper.cpp
        cocos/renderer/gfx-gles-new/egl/PBufferSurface.h
        cocos/renderer/gfx-gles-new/egl/PBufferSurface.cpp
        cocos/renderer/gfx-gles-new/egl/WindowSurface.h
        cocos/renderer/gfx-gles-new/egl/WindowSurface.cpp
        )
