export enum GamepadCode {
    // buttons
    A = 0,
    B = 1,
    X = 2,
    Y = 3,
    L1 = 4,
    R1 = 5,
    L2 = 6,
    R2 = 7,
    SHARE = 8,
    OPTIONS = 9,
    L3 = 10,
    R3 = 11,
    DPAD_UP = 12,
    DPAD_DOWN = 13,
    DPAD_LEFT = 14,
    DPAD_RIGHT = 15,
    HOME = 16,
    TOUCHPAD = 17,
    // axes
    AXIS_LEFT_STICK_X = 18,
    AXIS_LEFT_STICK_Y = 19,
    AXIS_RIGHT_STICK_X = 20,
    AXIS_RIGHT_STICK_Y = 21,
}
