#pragma once
#include "base/ccConfig.h"

#include "cocos/scripting/js-bindings/jswrapper/SeApi.h"

extern se::Object* __jsb_creator_Scale9SpriteV2_proto;
extern se::Class* __jsb_creator_Scale9SpriteV2_class;

bool js_register_creator_Scale9SpriteV2(se::Object* obj);
bool register_all_creator(se::Object* obj);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_setTexture);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_getFillType);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_isTrimmedContentSizeEnabled);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_getState);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_setState);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_setInsetBottom);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_setFillRange);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_getFillStart);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_getFillRange);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_setInsetTop);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_setRenderingType);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_setDistortionOffset);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_setFillCenter);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_setSpriteFrame);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_getBlendFunc);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_initWithTexture);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_getInsetLeft);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_getInsetBottom);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_setDistortionTiling);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_getRenderingType);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_setFillStart);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_getInsetRight);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_setBlendFunc);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_getFillCenter);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_getInsetTop);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_setInsetLeft);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_initWithSpriteFrame);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_setFillType);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_setInsetRight);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_enableTrimmedContentSize);
SE_DECLARE_FUNC(js_creator_Scale9SpriteV2_Scale9SpriteV2);

