#pragma once
#include "base/ccConfig.h"

#include "cocos/scripting/js-bindings/jswrapper/SeApi.h"

extern se::Object* __jsb_cocos2d_FileUtils_proto;
extern se::Class* __jsb_cocos2d_FileUtils_class;

bool js_register_cocos2d_FileUtils(se::Object* obj);
bool register_all_cocos2dx_global(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_writeDataToFile);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_fullPathForFilename);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_getStringFromFile);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_removeFile);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_getDataFromFile);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_isAbsolutePath);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_renameFile);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_normalizePath);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_getDefaultResourceRootPath);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_loadFilenameLookupDictionaryFromFile);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_isPopupNotify);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_getValueVectorFromFile);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_getSearchPaths);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_getFileDir);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_writeToFile);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_getOriginalSearchPaths);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_listFiles);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_getValueMapFromFile);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_getFileSize);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_getValueMapFromData);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_removeDirectory);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_setSearchPaths);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_writeStringToFile);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_setSearchResolutionsOrder);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_addSearchResolutionsOrder);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_addSearchPath);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_writeValueVectorToFile);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_isFileExist);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_purgeCachedEntries);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_fullPathFromRelativeFile);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_getSuitableFOpen);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_writeValueMapToFile);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_getFileExtension);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_setWritablePath);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_setPopupNotify);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_isDirectoryExist);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_setDefaultResourceRootPath);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_getSearchResolutionsOrder);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_createDirectory);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_listFilesRecursively);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_getWritablePath);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_setDelegate);
SE_DECLARE_FUNC(js_cocos2dx_global_FileUtils_getInstance);

extern se::Object* __jsb_cocos2d_Device_proto;
extern se::Class* __jsb_cocos2d_Device_class;

bool js_register_cocos2d_Device(se::Object* obj);
bool register_all_cocos2dx_global(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_global_Device_getNetworkType);
SE_DECLARE_FUNC(js_cocos2dx_global_Device_setAccelerometerEnabled);
SE_DECLARE_FUNC(js_cocos2dx_global_Device_setAccelerometerInterval);
SE_DECLARE_FUNC(js_cocos2dx_global_Device_vibrate);
SE_DECLARE_FUNC(js_cocos2dx_global_Device_setKeepScreenOn);
SE_DECLARE_FUNC(js_cocos2dx_global_Device_getBatteryLevel);
SE_DECLARE_FUNC(js_cocos2dx_global_Device_getDeviceRotation);
SE_DECLARE_FUNC(js_cocos2dx_global_Device_getDPI);
SE_DECLARE_FUNC(js_cocos2dx_global_Device_getDeviceModel);

extern se::Object* __jsb_cocos2d_CanvasRenderingContext2D_proto;
extern se::Class* __jsb_cocos2d_CanvasRenderingContext2D_class;

bool js_register_cocos2d_CanvasRenderingContext2D(se::Object* obj);
bool register_all_cocos2dx_global(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_restore);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_moveTo);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_lineTo);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_setTransform);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_stroke);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_measureText);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_scale);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_clearRect);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_transform);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_fillText);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_strokeText);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_save);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_fillRect);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_rotate);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_beginPath);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_translate);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_createLinearGradient);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_closePath);
SE_DECLARE_FUNC(js_cocos2dx_global_CanvasRenderingContext2D_CanvasRenderingContext2D);

