#pragma once
#include "base/ccConfig.h"

#include "cocos/scripting/js-bindings/jswrapper/SeApi.h"

extern se::Object* __jsb_cocos2d_extension_EventAssetsManagerEx_proto;
extern se::Class* __jsb_cocos2d_extension_EventAssetsManagerEx_class;

bool js_register_cocos2d_extension_EventAssetsManagerEx(se::Object* obj);
bool register_all_cocos2dx_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_extension_EventAssetsManagerEx_getAssetsManagerEx);
SE_DECLARE_FUNC(js_cocos2dx_extension_EventAssetsManagerEx_getDownloadedFiles);
SE_DECLARE_FUNC(js_cocos2dx_extension_EventAssetsManagerEx_getTotalFiles);
SE_DECLARE_FUNC(js_cocos2dx_extension_EventAssetsManagerEx_getAssetId);
SE_DECLARE_FUNC(js_cocos2dx_extension_EventAssetsManagerEx_getTotalBytes);
SE_DECLARE_FUNC(js_cocos2dx_extension_EventAssetsManagerEx_getCURLECode);
SE_DECLARE_FUNC(js_cocos2dx_extension_EventAssetsManagerEx_getMessage);
SE_DECLARE_FUNC(js_cocos2dx_extension_EventAssetsManagerEx_getCURLMCode);
SE_DECLARE_FUNC(js_cocos2dx_extension_EventAssetsManagerEx_getDownloadedBytes);
SE_DECLARE_FUNC(js_cocos2dx_extension_EventAssetsManagerEx_getPercentByFile);
SE_DECLARE_FUNC(js_cocos2dx_extension_EventAssetsManagerEx_getEventCode);
SE_DECLARE_FUNC(js_cocos2dx_extension_EventAssetsManagerEx_getPercent);
SE_DECLARE_FUNC(js_cocos2dx_extension_EventAssetsManagerEx_isResuming);
SE_DECLARE_FUNC(js_cocos2dx_extension_EventAssetsManagerEx_EventAssetsManagerEx);

extern se::Object* __jsb_cocos2d_extension_Manifest_proto;
extern se::Class* __jsb_cocos2d_extension_Manifest_class;

bool js_register_cocos2d_extension_Manifest(se::Object* obj);
bool register_all_cocos2dx_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_extension_Manifest_getManifestRoot);
SE_DECLARE_FUNC(js_cocos2dx_extension_Manifest_setUpdating);
SE_DECLARE_FUNC(js_cocos2dx_extension_Manifest_getManifestFileUrl);
SE_DECLARE_FUNC(js_cocos2dx_extension_Manifest_isVersionLoaded);
SE_DECLARE_FUNC(js_cocos2dx_extension_Manifest_parseFile);
SE_DECLARE_FUNC(js_cocos2dx_extension_Manifest_isLoaded);
SE_DECLARE_FUNC(js_cocos2dx_extension_Manifest_getPackageUrl);
SE_DECLARE_FUNC(js_cocos2dx_extension_Manifest_isUpdating);
SE_DECLARE_FUNC(js_cocos2dx_extension_Manifest_getVersion);
SE_DECLARE_FUNC(js_cocos2dx_extension_Manifest_parseJSONString);
SE_DECLARE_FUNC(js_cocos2dx_extension_Manifest_getVersionFileUrl);
SE_DECLARE_FUNC(js_cocos2dx_extension_Manifest_getSearchPaths);
SE_DECLARE_FUNC(js_cocos2dx_extension_Manifest_Manifest);

extern se::Object* __jsb_cocos2d_extension_AssetsManagerEx_proto;
extern se::Class* __jsb_cocos2d_extension_AssetsManagerEx_class;

bool js_register_cocos2d_extension_AssetsManagerEx(se::Object* obj);
bool register_all_cocos2dx_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_getDownloadedFiles);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_getState);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_getMaxConcurrentTask);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_getTotalFiles);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_loadRemoteManifest);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_checkUpdate);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_getTotalBytes);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_setVerifyCallback);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_getStoragePath);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_update);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_setVersionCompareHandle);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_setMaxConcurrentTask);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_getDownloadedBytes);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_getLocalManifest);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_loadLocalManifest);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_getRemoteManifest);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_prepareUpdate);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_downloadFailedAssets);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_isResuming);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_create);
SE_DECLARE_FUNC(js_cocos2dx_extension_AssetsManagerEx_AssetsManagerEx);

extern se::Object* __jsb_cocos2d_extension_EventListenerAssetsManagerEx_proto;
extern se::Class* __jsb_cocos2d_extension_EventListenerAssetsManagerEx_class;

bool js_register_cocos2d_extension_EventListenerAssetsManagerEx(se::Object* obj);
bool register_all_cocos2dx_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_extension_EventListenerAssetsManagerEx_EventListenerAssetsManagerEx);

extern se::Object* __jsb_cocos2d_extension_Control_proto;
extern se::Class* __jsb_cocos2d_extension_Control_class;

bool js_register_cocos2d_extension_Control(se::Object* obj);
bool register_all_cocos2dx_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_extension_Control_setEnabled);
SE_DECLARE_FUNC(js_cocos2dx_extension_Control_getState);
SE_DECLARE_FUNC(js_cocos2dx_extension_Control_sendActionsForControlEvents);
SE_DECLARE_FUNC(js_cocos2dx_extension_Control_setSelected);
SE_DECLARE_FUNC(js_cocos2dx_extension_Control_isEnabled);
SE_DECLARE_FUNC(js_cocos2dx_extension_Control_needsLayout);
SE_DECLARE_FUNC(js_cocos2dx_extension_Control_hasVisibleParents);
SE_DECLARE_FUNC(js_cocos2dx_extension_Control_isSelected);
SE_DECLARE_FUNC(js_cocos2dx_extension_Control_isTouchInside);
SE_DECLARE_FUNC(js_cocos2dx_extension_Control_setHighlighted);
SE_DECLARE_FUNC(js_cocos2dx_extension_Control_getTouchLocation);
SE_DECLARE_FUNC(js_cocos2dx_extension_Control_isHighlighted);
SE_DECLARE_FUNC(js_cocos2dx_extension_Control_create);
SE_DECLARE_FUNC(js_cocos2dx_extension_Control_Control);

extern se::Object* __jsb_cocos2d_extension_ControlButton_proto;
extern se::Class* __jsb_cocos2d_extension_ControlButton_class;

bool js_register_cocos2d_extension_ControlButton(se::Object* obj);
bool register_all_cocos2dx_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_isPushed);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_setTitleLabelForState);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_setAdjustBackgroundImage);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_setTitleForState);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_setLabelAnchorPoint);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_getLabelAnchorPoint);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_initWithBackgroundSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_getTitleTTFSizeForState);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_setTitleTTFForState);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_setTitleTTFSizeForState);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_setTitleLabel);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_setPreferredSize);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_getCurrentTitleColor);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_setZoomOnTouchDown);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_setBackgroundSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_getBackgroundSpriteForState);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_getHorizontalOrigin);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_initWithTitleAndFontNameAndFontSize);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_setTitleBMFontForState);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_getScaleRatio);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_getTitleTTFForState);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_getBackgroundSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_getTitleColorForState);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_setTitleColorForState);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_doesAdjustBackgroundImage);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_setBackgroundSpriteFrameForState);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_setBackgroundSpriteForState);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_setScaleRatio);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_getTitleBMFontForState);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_getTitleLabel);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_getPreferredSize);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_getVerticalMargin);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_getTitleLabelForState);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_setMargins);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_getCurrentTitle);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_initWithLabelAndBackgroundSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_getZoomOnTouchDown);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_getTitleForState);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_create);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlButton_ControlButton);

extern se::Object* __jsb_cocos2d_extension_ControlHuePicker_proto;
extern se::Class* __jsb_cocos2d_extension_ControlHuePicker_class;

bool js_register_cocos2d_extension_ControlHuePicker(se::Object* obj);
bool register_all_cocos2dx_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlHuePicker_initWithTargetAndPos);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlHuePicker_setHue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlHuePicker_getStartPos);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlHuePicker_getHue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlHuePicker_getSlider);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlHuePicker_setBackground);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlHuePicker_setHuePercentage);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlHuePicker_getBackground);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlHuePicker_getHuePercentage);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlHuePicker_setSlider);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlHuePicker_create);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlHuePicker_ControlHuePicker);

extern se::Object* __jsb_cocos2d_extension_ControlSaturationBrightnessPicker_proto;
extern se::Class* __jsb_cocos2d_extension_ControlSaturationBrightnessPicker_class;

bool js_register_cocos2d_extension_ControlSaturationBrightnessPicker(se::Object* obj);
bool register_all_cocos2dx_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSaturationBrightnessPicker_getShadow);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSaturationBrightnessPicker_initWithTargetAndPos);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSaturationBrightnessPicker_getStartPos);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSaturationBrightnessPicker_getOverlay);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSaturationBrightnessPicker_getSlider);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSaturationBrightnessPicker_getBackground);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSaturationBrightnessPicker_getSaturation);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSaturationBrightnessPicker_getBrightness);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSaturationBrightnessPicker_create);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSaturationBrightnessPicker_ControlSaturationBrightnessPicker);

extern se::Object* __jsb_cocos2d_extension_ControlColourPicker_proto;
extern se::Class* __jsb_cocos2d_extension_ControlColourPicker_class;

bool js_register_cocos2d_extension_ControlColourPicker(se::Object* obj);
bool register_all_cocos2dx_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlColourPicker_hueSliderValueChanged);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlColourPicker_getHuePicker);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlColourPicker_getcolourPicker);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlColourPicker_setBackground);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlColourPicker_setcolourPicker);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlColourPicker_colourSliderValueChanged);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlColourPicker_setHuePicker);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlColourPicker_getBackground);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlColourPicker_create);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlColourPicker_ControlColourPicker);

extern se::Object* __jsb_cocos2d_extension_ControlPotentiometer_proto;
extern se::Class* __jsb_cocos2d_extension_ControlPotentiometer_class;

bool js_register_cocos2d_extension_ControlPotentiometer(se::Object* obj);
bool register_all_cocos2dx_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_setPreviousLocation);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_setValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_getProgressTimer);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_getMaximumValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_angleInDegreesBetweenLineFromPoint_toPoint_toLineFromPoint_toPoint);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_potentiometerBegan);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_setMaximumValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_getMinimumValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_setThumbSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_getValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_getPreviousLocation);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_distanceBetweenPointAndPoint);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_potentiometerEnded);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_setProgressTimer);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_setMinimumValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_getThumbSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_initWithTrackSprite_ProgressTimer_ThumbSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_potentiometerMoved);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_create);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlPotentiometer_ControlPotentiometer);

extern se::Object* __jsb_cocos2d_extension_ControlSlider_proto;
extern se::Class* __jsb_cocos2d_extension_ControlSlider_class;

bool js_register_cocos2d_extension_ControlSlider(se::Object* obj);
bool register_all_cocos2dx_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_setBackgroundSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_getMaximumAllowedValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_initWithSprites);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_getMinimumAllowedValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_getMaximumValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_getSelectedThumbSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_setProgressSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_setMaximumValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_getMinimumValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_setThumbSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_getValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_getBackgroundSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_getThumbSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_setValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_locationFromTouch);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_setMinimumValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_setMinimumAllowedValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_getProgressSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_setSelectedThumbSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_setMaximumAllowedValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_create);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSlider_ControlSlider);

extern se::Object* __jsb_cocos2d_extension_ControlStepper_proto;
extern se::Class* __jsb_cocos2d_extension_ControlStepper_class;

bool js_register_cocos2d_extension_ControlStepper(se::Object* obj);
bool register_all_cocos2dx_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_getMinusSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_setValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_setStepValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_initWithMinusSpriteAndPlusSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_setValueWithSendingEvent);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_setMaximumValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_getMinusLabel);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_getPlusLabel);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_setWraps);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_setMinusLabel);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_startAutorepeat);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_updateLayoutUsingTouchLocation);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_isContinuous);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_stopAutorepeat);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_setMinimumValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_setPlusLabel);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_getValue);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_getPlusSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_setPlusSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_setMinusSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_create);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlStepper_ControlStepper);

extern se::Object* __jsb_cocos2d_extension_ControlSwitch_proto;
extern se::Class* __jsb_cocos2d_extension_ControlSwitch_class;

bool js_register_cocos2d_extension_ControlSwitch(se::Object* obj);
bool register_all_cocos2dx_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSwitch_setOn);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSwitch_locationFromTouch);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSwitch_isOn);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSwitch_initWithMaskSprite);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSwitch_hasMoved);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSwitch_create);
SE_DECLARE_FUNC(js_cocos2dx_extension_ControlSwitch_ControlSwitch);

extern se::Object* __jsb_cocos2d_extension_ScrollView_proto;
extern se::Class* __jsb_cocos2d_extension_ScrollView_class;

bool js_register_cocos2d_extension_ScrollView(se::Object* obj);
bool register_all_cocos2dx_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_isClippingToBounds);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_setContainer);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_setContentOffsetInDuration);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_setZoomScaleInDuration);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_updateTweenAction);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_setMaxScale);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_hasVisibleParents);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_getDirection);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_getContainer);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_setMinScale);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_getZoomScale);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_updateInset);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_initWithViewSize);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_pause);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_setDirection);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_stopAnimatedContentOffset);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_setContentOffset);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_isDragging);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_isTouchEnabled);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_isBounceable);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_setTouchEnabled);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_getContentOffset);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_resume);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_setClippingToBounds);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_setViewSize);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_getViewSize);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_maxContainerOffset);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_setBounceable);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_isTouchMoved);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_isNodeVisible);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_minContainerOffset);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_setZoomScale);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_create);
SE_DECLARE_FUNC(js_cocos2dx_extension_ScrollView_ScrollView);

extern se::Object* __jsb_cocos2d_extension_TableViewCell_proto;
extern se::Class* __jsb_cocos2d_extension_TableViewCell_class;

bool js_register_cocos2d_extension_TableViewCell(se::Object* obj);
bool register_all_cocos2dx_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableViewCell_reset);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableViewCell_getIdx);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableViewCell_setIdx);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableViewCell_create);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableViewCell_TableViewCell);

extern se::Object* __jsb_cocos2d_extension_TableView_proto;
extern se::Class* __jsb_cocos2d_extension_TableView_class;

bool js_register_cocos2d_extension_TableView(se::Object* obj);
bool register_all_cocos2dx_extension(se::Object* obj);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableView_updateCellAtIndex);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableView_setVerticalFillOrder);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableView_scrollViewDidZoom);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableView__updateContentSize);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableView_getVerticalFillOrder);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableView_removeCellAtIndex);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableView_initWithViewSize);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableView_scrollViewDidScroll);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableView_reloadData);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableView_insertCellAtIndex);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableView_cellAtIndex);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableView_dequeueCell);
SE_DECLARE_FUNC(js_cocos2dx_extension_TableView_TableView);

