
import { CanvasComponent} from './components/canvas-component';
import { UIRenderComponent} from './components/ui-render-component';
import { SpriteComponent} from './components/sprite-component';
import { UITransformComponent } from './components/ui-transfrom-component';
// import LabelComponent from './components/label-component';
// import {UITransformComponent} from './components/ui-transfrom-componentent';
// import ButtonComponent from './components/button-component';
// import ToggleGroupComponent from './components/toggle-group-component';
// import ToggleComponent from './components/toggle-component';
// import ToggleContainerComponent from './components/toggle-container-component';
// import SliderComponent from './components/slider-component';
// import ProgressBarComponent from './components/progress-bar-component';
// import WidgetComponent from './components/widget-component';
// import EditBoxComponent from './components/editbox/edit-box-component';
import './assembler/index';

cc.CanvasComponent = CanvasComponent;
cc.UIRenderComponent = UIRenderComponent;
cc.SpriteComponent = SpriteComponent;
// cc.LabelComponent = LabelComponent;
// cc.UIRectComponent = UIRectComponent;
// cc.ButtonComponent = ButtonComponent;
// cc.ToggleGroupComponent = ToggleGroupComponent;
// cc.ToggleComponent = ToggleComponent;
// cc.ToggleContainerComponent = ToggleContainerComponent;
// cc.SliderComponent = SliderComponent;
// cc.ProgressBarComponent = ProgressBarComponent;
// cc.WidgetComponent = WidgetComponent;
// cc.EditBoxComponent = EditBoxComponent;
