export enum Feature {
    CANVAS = 'CANVAS',
    GL = 'GL',
    WEBGL2 = 'WEBGL2',
    WEBP = 'WEBP',
    IMAGE_BIT_MAP = 'IMAGE_BIT_MAP',

    INPUT_KEYBOARD = 'INPUT_KEYBOARD',
    INPUT_MOUSE = 'INPUT_MOUSE',
    INPUT_TOUCH = 'INPUT_TOUCH',
    INPUT_ACCELEROMETER = 'INPUT_ACCELEROMETER',
}
