export enum Feature {
    WEBP = 'WEBP',
    IMAGE_BITMAP = 'IMAGE_BITMAP',
    WEB_VIEW = 'WEB_VIEW',
    VIDEO_PLAYER = 'VIDEO_PLAYER',
    SAFE_AREA = 'SAFE_AREA',

    INPUT_TOUCH = 'INPUT_TOUCH',
    EVENT_KEYBOARD = 'EVENT_KEYBOARD',
    EVENT_MOUSE = 'EVENT_MOUSE',
    EVENT_TOUCH = 'EVENT_TOUCH',
    EVENT_ACCELEROMETER = 'EVENT_ACCELEROMETER',
}
