export enum Feature {
    CANVAS = 'CANVAS',
    WEBGL = 'WEBGL',
    WEBGL2 = 'WEBGL2',
    WEBP = 'WEBP',
    IMAGE_BITMAP = 'IMAGE_BITMAP',
    WEB_VIEW = 'WEB_VIEW',
    VIDEO_PLAYER = 'VIDEO_PLAYER',
    SAFE_AREA = 'SAFE_AREA',

    INPUT_KEYBOARD = 'INPUT_KEYBOARD',
    INPUT_MOUSE = 'INPUT_MOUSE',
    INPUT_TOUCH = 'INPUT_TOUCH',
    INPUT_ACCELEROMETER = 'INPUT_ACCELEROMETER',
}
