name: quality
on: [push, pull_request]
jobs:
  eslint:
    name: Run ESLint
    if: github.actor!= 'dependabot'   # ignore the pull request which comes from user dependabot. See https://github.community/t/how-to-stop-github-actions-workflow-to-trigger-when-the-pull-request-is-from-dependabot-preview/116486/3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: Run ESLint
        shell: pwsh
        run: ./.github/workflows/eslint.ps1
